version: "3.9"

services:

# ############
# Django App
# ############
  backend:
    container_name: "backend"
    build: .
    command: > 
      sh -c 
        "python3 core/manage.py migrate &&
         python3 core/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db

# ############
# PgAdmin
# ############
  pgadmin:
    image: dpage/pgadmin4:2023-12-12-1
    container_name: pgadmin-db
    ports:
      - "5051:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

# ############
# PostgreSQL Database
# ############
  db:
    image: postgres:16.1-bullseye
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=blog_password
      - POSTGRES_DB=blog_db


volumes:
  postgres_data:
  pgadmin_data:
