version: "3.9"

services:

  backend:
    container_name: "backend"
    build: .
    command: > 
      sh -c 
        "python3 core/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:latest
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=blog_user
      - POSTGRES_PASSWORD=blog_password
      - POSTGRES_DB=blog_db


volumes:
  postgres_data:
