version: "3.9"

services:

  backend:
    container_name: "backend"
    build: .
    command: python3 core/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    container_name: postgres-db


volumes:
  postgres_data: