# Generated by Django 4.2.7 on 2023-11-18 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=255, unique_for_date='published_at'),
            preserve_default=False,
        ),
    ]
